### ISSUE TITLE
Error: multiple matching functions (argument="name", value="initialize", code=INVALID_ARGUMENT, version=abi/5.4.0)

### ISSUE THREAD

**Issue by TheDAS-designer** [sushiswap/shoyu#3]
![image](https://user-images.githubusercontent.com/69261567/125182258-15b60700-e23f-11eb-9fbc-70470a5c0d8c.png)
`import {ethers, upgrades} from "hardhat";
import { expect } from "chai";

describe("NFT721", async () => {
    it("tests upgrades.deployProxy ", async() => {
        const NFT721 = await ethers.getContractFactory("NFT721");
        const nft721 = await upgrades.deployProxy(NFT721,
            ['', 'aa', 'bb', '0xBC8F16D2aeE17B096FC5ED558ABc8923425157C4', [0,1], '0xBC8F16D2aeE17B096FC5ED558ABc8923425157C4', 5]
            , {initializer: "initialize"});

        expect((await nft721.address)).to.not('')
})})`

**Comment by levx-io** [comment]
shoyu contracts weren't designed for upgradeability

**Comment by TheDAS-designer** [comment]
> shoyu contracts weren't designed for upgradeability
Thanks for your reply.
But I don’t understand why it is designed to be non-upgradeable😥
