### ISSUE TITLE
Testing infrastructure plans?

### ISSUE THREAD

**Issue by SteversIO** [sushiswap/shoyu#40]
Hey all,

We'd love to explore contributing to this project. Are you planning on rolling out testing in the near term? I think longterm exhausive unit testing is necessary for large-scale adoption?

[OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/test/TESTING.md) moved to hardhat ~10 months ago iirc and are using mocha/chai.

**Comment by levx-io** [comment]
You can check them here: https://github.com/sushiswap/shoyu/tree/master/test
