### ISSUE TITLE
Implement EIP2981 for royalties

### ISSUE THREAD

**Issue by blmalone** [sushiswap/shoyu#5]
I've noticed you've got a royalty implementation for erc721 and erc1155. 
https://github.com/sushiswap/shoyu/blob/bdc4863d9ce07dbf670bcf0a6327663dad9aee2a/contracts/interfaces/IBaseExchange.sol#L23

Have you considered this finalized EIP for communicating royalty information? 
https://eips.ethereum.org/EIPS/eip-2981

**Comment by blmalone** [comment]
@levx-io 

Cool, I'm a contributor to the standard so let me know if you need any help. I think it would be a great addition to this project.

**Comment by levx-io** [comment]
Which other projects are adopting it?

**Comment by blmalone** [comment]
It just got finalized last week. 

https://github.com/manifoldxyz/royalty-registry-solidity/ is using it and currently in talks with NFT exchanges :)

**Comment by cliffhall** [comment]
I've implemented it in both the new KnownOrigin and Seen.Haus contract suite. I can also provide some input if needed.

**Comment by dievardump** [comment]
I'm also implementing it in every NFT and Exchange contracts I do as a Solidity dev.

Also implemented it on BeyondNFT where possible and plan to implement new Exchange and NFT contracts with its support soon.

I know other developers like the Manifold guys do have that per default in their CreatorCore contracts. 

example: https://etherscan.io/address/0x00372812abcb11c2ea291aeb7f612d9e0524b013#code#F21#L1

**Comment by levx-io** [comment]
Merged #11

**Comment by blmalone** [comment]
@levx-io nice one!
